### ISSUE TITLE
Can I use this project as cashless device?

### ISSUE THREAD

**Issue by malekses** [Tarcontar/ArduinoMDB#6]
I would like to use this project as cashless device, just sending balance to the vending machine.
Is it possible?

**Comment by Tarcontar** [comment]
Hi,
Sure you can use it for that.
But that would require some work, since that was not really the intention of this project.

Cheers
Tarcontar

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: malekses ***@***.***>
Sent: Friday, June 3, 2022 5:37:37 PM
To: Tarcontar/ArduinoMDB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Tarcontar/ArduinoMDB] Can I use this project as cashless device? (Issue #6)


I would like to use this project as cashless device, just sending balance to the vending machine.
Is it possible?
